name:                langchain-hs
version:             0.0.1.0
github:              "tusharad/langchain-hs"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"
category:            Web
synopsis:           "Haskell implementation of Langchain"
extra-source-files:
- README.md
- CHANGELOG.md

description: Build LLM-powered applications in Haskell.

dependencies:
- base >= 4.7 && < 5
- text >= 2 && < 3
- aeson >= 2 && < 3
- bytestring >= 0.10
- containers >= 0.6 && < 0.9
- directory >= 1.3.6 && < 1.4
- pdf-toolbox-document == 0.1.4
- ollama-haskell
- scalpel >= 0.6 && < 0.7
- http-types >= 0.11 && < 0.13
- http-conduit >= 2 && < 3
- conduit >= 1.2 && < 1.4
- filepath
- async

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  langchain-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-hs
    - text
    - tasty
    - tasty-hunit
    - filepath
    - temporary
