name:                langchain-examples
version:             0.1.0.0
github:              "tusharad/langchain-examples"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A series of examples which are using langchain-hs

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- langchain-hs
- transformers
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  langchain-examples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-examples

tests:
  langchain-examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-examples
